InventoryTracker/InventoryTracker/urls.py
"""
Definition of urls for InventoryTracker.
"""
from typing import Union, List

from django.urls import path, URLPattern, URLResolver
from django.conf.urls import include, url
from django.contrib import admin
from app.views import index
from django.conf import settings
from django.conf.urls.static import static


urlpatterns: List[Union[URLPattern, URLResolver]] = [
    path('', index, name='index'),
    path('inv/', include('inventory.urls')),
    path('proj/', include('projects.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

InventoryTracker/app/urls.py
from django.urls import path
from django.conf.urls import include, url
from app import forms, views


urlpatterns = [
    path('', views.home, name='home'),
    path('add_part', views.AddPartBaseView.as_view(), name='add_part'),
    path('add_part/c', views.AddCapacitorView.as_view(), name='add_part_capacitor'),
    path('add_part/r', views.AddResistorView.as_view(), name='add_part_resistor'),

    path('projects', views.ProjectIndexView.as_view(), name='projects'),
    path('projects/<int:id>/bom', views.ProjectBOMView.as_view(), name='bom'),
]

InventoryTracker/projects/urls.py
from django.urls import path
from django.conf.urls import include, url

from . import views

app_name = 'projects'
urlpatterns = [
    path('<int:id>/bom', views.ProjectBOMView.as_view(), name='bom'),
    path('add', views.ProjectAddView.as_view(), name='add'),
    path('<int:id>/bom_upload', views.BomUpload.as_view(), name="csv_upload"),
    path('', views.ProjectIndexView.as_view(), name='home'),
]

InventoryTracker/projects/models.py
from django.db import models
from django.db.models import Sum, Q

# Create your models here.
class ProjectModel(models.Model):
    """
    Represents a project that will consume parts
    """
    Name = models.CharField(max_length=128,
                            help_text='Name of this project')

    Description = models.TextField(help_text="Description for this project")

    class Meta:
        verbose_name = 'Project'

    def __str__(self):
        return self.Name

class ProjectPartModel(models.Model):
    """
    Links a part to a project.
    """

    Quantity = models.IntegerField(help_text='Quantity of parts required')

    Part = models.ForeignKey('inventory.PartModel', on_delete=models.CASCADE,
                             help_text="Part required")

    Project = models.ForeignKey(ProjectModel, on_delete=models.CASCADE,
                                help_text='Project this part is required for')

    class Meta:
        verbose_name = 'Project Part'
        unique_together=['Part', 'Project']

    def __str__(self):
        return '{} - {}'.format(self.Part, self.Project)

    def GetDesignators(self):
        """
        Get a list of designators separated by comma
        """
        d = self.bomdesignatormodel_set.all()
        return ','.join([str(x) for x in d])

class BOMDesignatorModel(models.Model):
    """
    This is a designator that is applied to a project part.
    For example U2 or R7
    """

    Number = models.IntegerField(help_text='Numeric part of the designator')

    Letter = models.CharField(max_length=2,
                              help_text="Letter part of the designator")

    PartModel = models.ForeignKey(ProjectPartModel, on_delete=models.CASCADE,
                                  help_text='Project part this designator is applied to')

    class Meta:
        verbose_name='Part Designator'
        constraints = [
            models.UniqueConstraint(fields=['Number', 'Letter', 'PartModel'], name='BOMNumberLetterPartConstrant'),
            models.CheckConstraint(check=Q(Number__gte=0), name='BOMNumbergte0')
        ]

    def __str__(self):
        return self.Letter + str(self.Number)

InventoryTracker/projects/forms.py
from django import forms
from .models import ProjectModel

class AddProjectForm(forms.ModelForm):
    class Meta:
        model = ProjectModel
        fields = ['Name', 'Description']

class BOMUploadSelectForm(forms.Form):
    BOMFile = forms.FileField(help_text="BOM file to upload")

InventoryTracker/app/views/project_bom.py
from django.views.generic.base import TemplateView
from django.http import Http404

from app.models import ProjectPartModel

class ProjectBOMView(TemplateView):
    """
    Project index  templated view
    """
    template_name = "app/project_bom.html"

    def get(self, request, *args, **kwargs):
        if not 'id' in kwargs:
            raise Http404

        ID:int =int(kwargs['id'])

        self._ProjectParts = ProjectPartModel.objects.filter(Project__pk = ID)
        self._ProjectParts = self._ProjectParts.order_by('Part__Name')
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "BOM"
        context['Parts'] = self._ProjectParts
        return context

InventoryTracker/projects/views/add.py
from typing import Optional
from django.views.generic.base import TemplateView
from django.forms import Form
from django.shortcuts import redirect
from projects.models import ProjectModel
from projects.forms import AddProjectForm

class ProjectAddView(TemplateView):
    """
    Project index  templated view
    """
    template_name = "projects/add.html"

    def __init__(self, **kwargs):
        self.__Form: Optional[Form] = None;

        return super().__init__(**kwargs)

    def get(self, request, *args, **kwargs):
        self.__Form = AddProjectForm()
        return super().get(request, *args, **kwargs)

    def post(self, request, **kwargs):
        self.__Form = AddProjectForm(request.POST)
        if self.__Form.is_valid():
            try:
                m = ProjectModel(Name=self.__Form.cleaned_data['Name'],
                                 Description = self.__Form.cleaned_data['Description'])
                m.save()

                return redirect("projects:home")
            except:
                raise

        context = self.get_context_data(**kwargs)

        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.__Form
        context['title'] = "Projects"
        return context

InventoryTracker/projects/views/bom.py
from django.views.generic.base import TemplateView
from django.http import Http404

from projects.forms import BOMUploadSelectForm
from projects.models import ProjectPartModel

class ProjectBOMView(TemplateView):
    """
    Project index  templated view
    """
    template_name = "projects/bom.html"

    def get(self, request, *args, **kwargs):
        if not 'id' in kwargs:
            raise Http404

        self._ID: int =int(kwargs['id'])

        self._ProjectParts = ProjectPartModel.objects.filter(Project__pk = self._ID)
        self._ProjectParts = self._ProjectParts.order_by('Part__Name')
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['upload_form'] = BOMUploadSelectForm()
        context['title'] = "BOM"
        context['Parts'] = self._ProjectParts
        context['ID'] = self._ID
        return context

InventoryTracker/projects/views/bom_upload.py
import csv
import chardet
from io import StringIO, TextIOWrapper

from django.views.generic.base import TemplateView
from django.http import HttpRequest, HttpResponse

from projects.forms import BOMUploadSelectForm

class BomUpload(TemplateView):
    """
    Allows upload a CSV based BOM list
    """
    template_name = "projects/bom_upload.html"

    def __init__(self, **kwargs):
        self.__Form = BOMUploadSelectForm()
        super().__init__(**kwargs)

    def post(self, request: HttpRequest, **kwargs)->HttpResponse:
        self.__Form = BOMUploadSelectForm(request.POST, request.FILES)
        if self.__Form.is_valid():
            F = self.__Form.cleaned_data['BOMFile']
            detector = chardet.UniversalDetector()
            for line in F.readlines():
                detector.feed(line)
                if detector.done: break

            detector.close()
            CSVFile = TextIOWrapper(F, encoding=detector.result['encoding'], errors='strict' )
            CSVFile.seek(0)
            Reader = csv.reader(CSVFile)
            self.__Headers = next(Reader)
            self.__Data = list(Reader)

        context = self.get_context_data()
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "BOM Upload"
        context['form'] = self.__Form
        context['headers'] = self.__Headers
        context['data'] = self.__Data
        return context

InventoryTracker/projects/views/index.py
from django.views.generic.base import TemplateView

from projects.models import ProjectModel

class ProjectIndexView(TemplateView):
    """
    Project index  templated view
    """
    template_name = "projects/project_index.html"

    def get(self, request, *args, **kwargs):
        self._Projects = ProjectModel.objects.all().order_by('Name')
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Projects"
        context['Projects'] = self._Projects
        return context

InventoryTracker/projects/templates/projects/add.html
{% extends "app/layout.html" %}
{% load static %}

{% block content %}

<form action="{{ request.path }}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">        
        {{ field.label_tag }}
        {{ field }}
        {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text|safe }}</small>
        {% endif %}
        {{ field.errors }}
    </div>
{% endfor %}
    <input type="submit" class="btn btn-primary" value="Submit">
</form>

{% endblock %}

{% block scripts %}

{% endblock %}

InventoryTracker/projects/templates/projects/bom.html
{% extends "app/layout.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}

<div class="row">
<form action="{% url 'projects:csv_upload' ID %}" 
      method="post" 
      enctype="multipart/form-data" 
      class="col-6 col-xl-3"
      id="BOMUploadForm">
    {% csrf_token %}
    <div class="form-group">        
		<small class="form-text text-muted">{{ upload_form.BOMFile.help_text|safe }}</small>
		{% render_field upload_form.BOMFile class+="form-control-file" %}
    </div>
</form>
</div>

<table id="project_table" class="display">
    <thead>
        <tr>
            <th>Part</th>
			<th>Value</th>
            <th>Package</th>
			<th>Quantity</th>
			<th>On Hand</th>
			<th>Designator</th>
        </tr>
    </thead>
    <tbody>
		{% for p in Parts %}
		<tr>
			<td>{{ p.Part.Category.CategoryName }}</td>
			<td>{{ p.Part.GetValue }}</td>
			<td>{{ p.Part.Package.Name }}</td>
			<td>{{ p.Quantity }}</td>
			<td>{{ p.Part.GetAvailable }}</td>
			<td>{{ p.GetDesignators }}</td>
		</tr>
		{% endfor %}
    </tbody>
</table>

{% endblock %}

{% block scripts %}
<script type="text/javascript" href="{% static 'app/scripts/app_const.js' %}"></script>

<script type="text/javascript">

    $(document).ready(function () {
        var table = $('#project_table').DataTable({});

        $("#BOMUploadForm input[type=file]").change(function () {
            $("#BOMUploadForm").submit();
        });
    });

</script>
{% endblock %}

InventoryTracker/projects/templates/projects/bom_upload.html
{% extends "app/layout.html" %}
{% load static %}

{% block content %}

<div>
<table id="PartTable">
    <thead>
        <tr>
            {% for header in headers %}
            <th>
            <select data-column="{{header}}" data-col-indx="{{ forloop.counter0 }}">
                <option>Select</option>
            </select>
            </th>
            {% endfor %}
        </tr>
        <tr>
            {% for header in headers %}
            <th>{{header}}</th>
            {% endfor %}
            <th>Part Link</th>
        </tr>
    </thead>
    <tbody>
        {% for row in data %}
        <tr>
            {% for cell in row %}
            <td>{{cell}}</td>
            {% endfor %}
            <td><input id="tags"></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript">

    var ColumnTypes = new Map();
    ColumnTypes.set("Designator", 'D');
    ColumnTypes.set("Name", 'N');

    $(document).ready(function () {
        var AutoMenu = $("#tags").autocomplete({
            source: '/inv/search',
        });

        AutoMenu.data("ui-autocomplete")._renderItem = function (ul, item) {
            var T = 1;
            return $("<li>")
                .attr("data-value", item.value)
                .append(item.label)
                .appendTo(ul);
        };

        var table = $('#PartTable').DataTable({
            responsive: true,
            "autoWidth": false
        });

        $("select[data-column]").each(function (indx) {
            $(this).append(new Option("Ignore", "I", false, false));
            $(this).change(function (d) {
                var v = this.value;
                var indx = $(this).data("col-indx");
                if (v == 'I') {
                    table.column(indx).visible(false);
                }

                table.responsive.recalc();
            });
        });
    });

</script>
{% endblock %}

InventoryTracker/projects/templates/projects/index.html
{% extends "app/layout.html" %}
{% load static %}
{% block content %}

<div class="btn-header">
	<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
		<div class="btn-group mr-2" role="group" aria-label="First group">
			<a class="btn btn-secondary" href="{% url 'projects:add' %}">Create Project</a>
		</div>
	</div>
</div>

<table id="project_table" class="display">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
			<th>BOM</th>
        </tr>
    </thead>
    <tbody>
		{% for p in Projects %}
		<tr>
			<td>{{ p.Name }}</td>
			<td>{{ p.Description }}</td>
			<td><a href="{% url 'projects:bom' id=p.pk %}">BOM</a></td>
		</tr>
		{% endfor %}
    </tbody>
</table>

{% endblock %}

{% block scripts %}
<script type="text/javascript" href="{% static 'app/scripts/app_const.js' %}"></script>
<script type="text/javascript">

	$(document).ready(function () {
		var table = $('#project_table').DataTable({});
	});

</script>
{% endblock %}

InventoryTracker/projects/templates/projects/project_bom.html
{% extends "app/layout.html" %}
{% load static %}
{% block content %}

<table id="project_table" class="display">
    <thead>
        <tr>
            <th>Part</th>
			<th>Value</th>
            <th>Package</th>
			<th>Quantity</th>
			<th>On Hand</th>
			<th>Designator</th>
        </tr>
    </thead>
    <tbody>
		{% for p in Parts %}
		<tr>
			<td>{{ p.Part.Category.CategoryName }}</td>
			<td>{{ p.Part.GetValue }}</td>
			<td>{{ p.Part.Package.Name }}</td>
			<td>{{ p.Quantity }}</td>
			<td>{{ p.Part.GetAvailable }}</td>
			<td>{{ p.GetDesignators }}</td>
		</tr>
		{% endfor %}
    </tbody>
</table>

{% endblock %}

{% block scripts %}
<script type="text/javascript" href="{% static 'app/scripts/app_const.js' %}"></script>
<script type="text/javascript">

	$(document).ready(function () {
		var table = $('#project_table').DataTable({});
	});

</script>
{% endblock %}