InventoryTracker/InventoryTracker/urls.py
"""
Definition of urls for InventoryTracker.
"""
from typing import Union, List

from django.urls import path, URLPattern, URLResolver
from django.conf.urls import include, url
from django.contrib import admin
from app.views import index
from django.conf import settings
from django.conf.urls.static import static


urlpatterns: List[Union[URLPattern, URLResolver]] = [
    path('', index, name='index'),
    path('inv/', include('inventory.urls')),
    path('proj/', include('projects.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

InventoryTracker/app/urls.py
from django.urls import path
from django.conf.urls import include, url
from app import forms, views


urlpatterns = [
    path('', views.home, name='home'),
    path('add_part', views.AddPartBaseView.as_view(), name='add_part'),
    path('add_part/c', views.AddCapacitorView.as_view(), name='add_part_capacitor'),
    path('add_part/r', views.AddResistorView.as_view(), name='add_part_resistor'),

    path('projects', views.ProjectIndexView.as_view(), name='projects'),
    path('projects/<int:id>/bom', views.ProjectBOMView.as_view(), name='bom'),
]

InventoryTracker/inventory/urls.py
from django.urls import path
from django.conf.urls import include, url


from inventory import forms, views

app_name = 'inventory'


urlpatterns = [
    path('', views.home, name='home'),
    path('add_part', views.AddPartBaseView.as_view(), name='add_part'),
    path('add_part/c', views.AddCapacitorView.as_view(), name='add_part_capacitor'),
    path('add_part/r', views.AddResistorView.as_view(), name='add_part_resistor'),
    path('search', views.PartSearch.as_view(), name='part_search'),
]

InventoryTracker/projects/urls.py
from django.urls import path
from django.conf.urls import include, url

from . import views

app_name = 'projects'
urlpatterns = [
    path('<int:id>/bom', views.ProjectBOMView.as_view(), name='bom'),
    path('add', views.ProjectAddView.as_view(), name='add'),
    path('<int:id>/bom_upload', views.BomUpload.as_view(), name="csv_upload"),
    path('', views.ProjectIndexView.as_view(), name='home'),
]

InventoryTracker/app/views/project_index.py
from django.views.generic.base import TemplateView

from app.models import ProjectModel

class ProjectIndexView(TemplateView):
    """
    Project index  templated view
    """
    template_name = "app/project_index.html"

    def get(self, request, *args, **kwargs):
        self._Projects = ProjectModel.objects.all().order_by('Name')
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Projects"
        context['Projects'] = self._Projects
        return context

InventoryTracker/app/templates/app/index.html
{% extends "app/layout.html" %}
{% load static %}
{% block content %}
<table id="part_table" class="display">
    <thead>
        <tr>
			<th></th>
            <th>Value</th>
            <th>Package</th>
            <th>Category</th>
        </tr>
    </thead>
    <tbody>
		{% for part in parts %}
		<tr>
			<td></td>
			<td>{{part.GetValue}}</td>
			<td>{{ part.Package.Name }}</td>
			<td>{{ part.Category.CategoryName }}</td>
		</tr>
		{% endfor %}
    </tbody>
</table>

{% endblock %}

{% block scripts %}
<script type="text/javascript" href="{% static 'app/scripts/app_const.js' %}"></script>
<script type="text/javascript">

	/* Formatting function for row details - modify as you need */
	function format(d) {
		// `d` is the original data object for the row
		return '<table class="part-sub-table">' +
			"<thead>" +
			"<tr>" +
			"<th>Shelf</th>" +
			"<th>Container ID</th>" +
			"<th>Quantity</th>" +
			"</tr>" +
			"</thead>" +
			"<tbody></tbody>" +
			'</table>';
	}


	$(document).ready(function () {
		var table = $('#part_table').DataTable({
			/*"ajax": { url: '/api/latest/parts_all', dataSrc: '' },
			"columns": [
				{
					"className": 'details-control',
					"orderable": false,
					"data": null,
					"defaultContent": ''
				},
				{ data: 'Name' },
				{ data: 'Package.Name' },
				{ data: 'Catagory.CatagoryName' },
			]*/
		});

		/*
		// Add event listener for opening and closing details
		$('#part_table tbody').on('click', 'td.details-control', function () {
			var tr = $(this).closest('tr');
			var row = table.row(tr);

			if (row.child.isShown()) {
				// This row is already open - close it
				row.child.hide();
				tr.removeClass('shown');
			}
			else {
				// Open this row
				row.child(format(row.data())).show();
				$(".part-sub-table", row.child()).DataTable({
					data: row.data().partcountmodel_set,
					paging: false,
					searching: false,
					info : false,
					columns: [
						{ data: "Shelf.Name" },
						{ data: "Location" },
						{ data: "Quantity" },
					]
				});
				tr.addClass('shown');
			}
		});
		*/
	});

</script>
{% endblock %}

InventoryTracker/app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>{{ title }} - Inventory Tracker</title>
    {% else %}
    <title>Inventory Tracker</title>
    {% endif %}
    {% load static %}
    
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
          rel="stylesheet" 
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
          crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
  <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'index' %}">Inventory Tracker</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'inventory:add_part' %}">Add Part</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'projects:home' %}">Projects</a>
      </li>
        </ul>
  </div>
</nav>

    {% block notifications %}{% endblock %}

    <div class="container body-content">
{% block content %}{% endblock %}
    </div>

    <script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
    
{% block scripts %}{% endblock %}

</body>
</html>

InventoryTracker/app/templates/app/project_index.html
{% extends "app/layout.html" %}
{% load static %}
{% block content %}

<table id="project_table" class="display">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
		{% for p in Projects %}
		<tr>
			<td>{{ p.Name }}</td>
			<td>{{ p.Description }}</td>
		</tr>
		{% endfor %}
    </tbody>
</table>

{% endblock %}

{% block scripts %}
<script type="text/javascript" href="{% static 'app/scripts/app_const.js' %}"></script>
<script type="text/javascript">

	$(document).ready(function () {
		var table = $('#project_table').DataTable({});
	});

</script>
{% endblock %}